### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by d4l3k** [rhardih/serve#2]
I tried out your project but it seems to be throwing this error.

```
$ go get github.com/rhardih/serve

# github.com/rhardih/serve
../../go/src/github.com/rhardih/serve/serve.go:164: c.NArg undefined (type *cli.Context has no field or method NArg)
```

**Comment by rhardih** [comment]
I'm was unable to reproduce this error. I've tried removing the install and re-getting it.

Maybe you have an old version of `github.com/codegangsta/cli` checked out.

Could you try: `go get -u github.com/rhardih/serve` instead? This should update dependencies as well.

**Comment by rhardih** [comment]
@d4l3k Any luck?

**Comment by rhardih** [comment]
@d4l3k Please re-open this issue if you still see the problem.
