### ISSUE TITLE
Release (or install instruction) needs updating

### ISSUE THREAD

**Issue by simonwiles** [rhardih/serve#5]
The install instruction to:
```
go get github.com/rhardih/serve
```
doesn't appear to work:

```
go get: github.com/rhardih/serve@none updating to
        github.com/rhardih/serve@v1.1.0: parsing go.mod:
        module declares its path as: serve
                but was required as: github.com/rhardih/serve 
```

This is because the commit at 705a565 didn't make it into [v1.1.0](https://github.com/rhardih/serve/releases/tag/).  Ideally a new release should be made to include this commit.  Alternatively, the package can be installed successfully with:
```
go get github.com/rhardih/serve@master
```

It's worth the effort, as this is a really useful little tool!

**Comment by rhardih** [comment]
Thanks for looking out! I think it should be fixed now with the v1.1.1 tag. I tried it in two different containers with 1.15 and 1.16 and it seems to work.
